#!/usr/bin/env python
''' colourphon
author:      Tom Regan <thomas.c.regan@gmail.com>
since:       2011-07-12
description: Displays the colour palate available in a teminal.
'''

print '\n{:-^78}\n'.format('basic colors')
for a in range(255):
    if a % 8 == 0 and a > 0:
        print ''
    print "{:>2}:\033[{:}mAa\033[0m ".format(hex(a)[2:],a),

print '\n\n{:-^78}\n'.format('compound colors')
for a in range(22,40):
    for b in range(255):
        if b % 8 == 0:
            print ''
        print "{:>2};{:>2}:\033[{:};{:}mAa\033[0m ".format(hex(a)[2:],hex(b)[2:],a,b),
