#!/bin/bash
#
# Unit Test Runner.
# file           : run_tests
# author         : Tom Regan (thomas.c.regan@gmail.com)
# since          : 2011-07-27
# last modified  : 2011-08-03

for test in *test.py; do
	if [[ $test =~ exclude ]]; then
		echo -n "Skipping test:"
		echo $test | sed 's/exclude//;s/_/\ /g;s/\.py//;s/\(\w\)\(\w\+\)/\U\1\L\2/g'
		echo
	else
		echo $test | sed 's/_/\ /g;s/\.py//;s/\(\w\)\(\w\+\)/\U\1\L\2/g'
		./${test};
		echo
	fi;
done;
