#!/bin/bash
# Colourized logfile output

#colors
red='\e[31m'
gre='\e[32m'
yel='\e[33m'
blu='\e[34m'
pur='\e[35m'
cya='\e[36m'
whi='\e[37m'
rst='\e[0m'


FILE=$1
OUTFILE=$2
i=0
# tmp="##$(uuidgen)##"
# tac ${FILE} > $tmp
while read -r line; do
  if $(echo "${line}" | egrep -q '^\[c\]'); then
    echo -e "${red}${line}${rst}"
  elif $(echo "${line}" | egrep -q '^\[m\]'); then
    echo -e "${pur}${line}${rst}"
  elif $(echo "${line}" | egrep -q '^\[i\]'); then
    echo -e "${yel}${line}${rst}"
  else
    echo -e "${line}"
  fi
  i=$(( ${i} + 1 ))
done < $FILE > ${OUTFILE}
echo "processed ${i} lines"
# rm $tmp
